modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/Ketheroth/Uncrafter/issues"
[[mods]]
modId="uncrafter"
version="1.18.1-1.1.0"
displayName="Uncrafter"
updateJSONURL="https://ketheroth.com/mods/uncrafter.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/uncrafter"
logoFile="logo.png"
authors="Ketheroth"
description='''
Allow items to be uncrafted
'''
itemIcon="uncrafter:advanced_uncrafter"

[[dependencies.uncrafter]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.uncrafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
